version: "3.7"

x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "10"
      max-size: "100m"

services:
  beacon:
    container_name: beacon
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:${PRYSM_DOCKER_TAG}
    restart: always
    hostname: beacon
    # depends_on:
    #   - geth
    command: --config-file=/config/beacon.yaml
    ports:
      - 127.0.0.1:4000:4000
      - 13000:13000/tcp
      - 12000:12000/udp
    volumes:
      - ./config/beacon.yaml:/config/beacon.yaml:ro
      - ./beacon:/data
    <<: *logging
  validator:
    container_name: validator
    image: gcr.io/prysmaticlabs/prysm/validator:${PRYSM_DOCKER_TAG}
    restart: on-failure
    hostname: validator
    depends_on:
      - beacon
    command: --config-file=/config/validator.yaml
    ports:
      - 127.0.0.1:7500:7500
    volumes:
      - ./config/validator.yaml:/config/validator.yaml:ro
      - ./validator:/data
    <<: *logging
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.22.2
    user: root # https://github.com/prometheus/prometheus/issues/5976
    restart: on-failure
    hostname: prometheus
    command: --storage.tsdb.retention.time=31d --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    <<: *logging
  grafana:
    container_name: grafana
    image: grafana/grafana:7.3.3
    restart: on-failure
    hostname: grafana
    depends_on:
      - prometheus
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    <<: *logging
  # geth:
  #   container_name: geth
  #   image: ethereum/client-go:stable
  #   restart: always
  #   hostname: geth
  #   command: --rpc --rpcport=8545 --rpcaddr=0.0.0.0 --rpcvhosts="*" --allow-insecure-unlock --rpcapi="db,eth,net,web3,personal"
  #   ports:
  #     - 30303:30303/tcp
  #     - 30303:30303/udp
  #     - 127.0.0.1:8545:8545
  #   volumes:
  #     - ./geth:/root/.ethereum
  #   <<: *logging
  #   slasher:
  #     container_name: slasher
  #     image: gcr.io/prysmaticlabs/prysm/slasher:${PRYSM_DOCKER_TAG}
  #     restart: always
  #     hostname: slasher
  #     depends_on:
  #       - beacon
  #     command: --config-file=/config/slasher.yaml
  #     volumes:
  #       - ./config/slasher.yaml:/config/slasher.yaml:ro
  #       - ./slasher:/data
  #     <<: *logging

volumes:
  grafana_data:
