############################################################
##
## Read up on parameters on
## https://docs.prylabs.network/docs/prysm-usage/parameters/
##
############################################################

accept-terms-of-use: yes

# pyrmont: yes

datadir: /data

#######################
# Connectivity settings
p2p-host-ip: ""
p2p-host-dns: ""

rpc-host: 0.0.0.0
monitoring-host: 0.0.0.0
grpc-gateway-host: 0.0.0.0
grpc-gateway-corsdomain: http://127.0.0.1:7500
grpc-gateway-port: 3500

# disable scan of local network
p2p-denylist:
  [
    "10.0.0.0/8",
    "172.16.0.0/12",
    "192.168.0.0/16",
    "100.64.0.0/10",
    "169.254.0.0/16",
  ]

# changing this also needs to be changed in docker-compose.yaml!
p2p-tcp-port: 13000

# enable db backup endpoint
enable-db-backup-webhook: true

##############################
# Connection to geth container

# Local geth for testnet:
# http-web3provider: http://geth:8545

http-web3provider: https://cloudflare-eth.com/

blst: yes
